language: c

compiler:
  - gcc
before_install:
  - apt-get -qq update
  - apt-get install -y pkg-config libtool libcurl4-openssl-dev
before_script:
  - ./autogen.sh

script:
  - ./configure
  - make

sudo: false
